### ISSUE TITLE
window  size is hardcoded

### ISSUE THREAD

**Issue by MAmouni20** [MbarkErras/42sh-refactoring#2]
<img width="570" alt="Screen Shot 2019-10-14 at 2 51 21 PM" src="https://user-images.githubusercontent.com/32802212/66756640-61812400-ee92-11e9-8031-6c74ff907924.png">

**Comment by MbarkErras** [comment]
not interested in supporting this feature

**Comment by MbarkErras** [comment]
sorry gonna check it out

**Comment by MbarkErras** [comment]
fixed!
